### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by vitaly-t** [pgaubatz/node-promise-settle#1]
I've just ran into a need to use `Promise.settle`, like the one you implemented, to execute promise-queries inside a database transaction.

I just wanted to say thank you for providing an idea of how to implement it!

Is this your own implementation or an adopted version from a promise library?

I know there is a version of it included into [Bluebird](https://github.com/petkaantonov/bluebird), but it's a bit more complex than needed.

**Comment by pgaubatz** [comment]
Hi!

Sorry for the "somewhat delayed" answer! :)
Thanks for the kind words. I am glad that you like it.

It is my own implementation but the "API" has been adopted from Bluebird.

Cheers,
Patrick

**Comment by vitaly-t** [comment]
Thank you for coming back after this long :)

At this point though I ended up with my own implementation of this method: [spex.batch](https://github.com/vitaly-t/spex/blob/master/docs/code/batch.md)
