### ISSUE TITLE
UMD for browser

### ISSUE THREAD

**Issue by AndersDJohnson** [pgaubatz/node-promise-settle#2]
Would you consider a pull request adding UMD support? https://github.com/umdjs/umd/blob/master/commonjsStrictGlobal.js

I'm assuming this is compatible with [the standard Promise spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) coming to newer browsers.

**Comment by vitaly-t** [comment]
The author never replied to my original post, which makes me think it was never meant to have any serious support :)

Have you tried to use [browserify](https://github.com/substack/node-browserify) to port the code for the client-side?

**Comment by pgaubatz** [comment]
Hi!

I've just pushed d4e84130a78918c4f624861a17900a3e87857ba7. Does this solve your problem?

Regarding the standard Promise spec: Yes, it's compatible.

Cheers,
Patrick

**Comment by AndersDJohnson** [comment]
@pgaubatz Works well, thanks!

I'll only mention that it's not a true polyfill in case browsers ever implement this, as it seems the browersify wrapper code doesn't check for the existence of `Promise.settle` before overwriting.
