### ISSUE TITLE
Promise is said to be fulfilled when reject isn't given a reason

### ISSUE THREAD

**Issue by DannyBrown-xx** [pgaubatz/node-promise-settle#4]
Given the following code:

```
import settle from 'promise-settle';

function aPromiseMethod() {
  return new Promise((resolve, reject) => {
    reject();
  });
}

settle([aPromiseMethod()]).then(results => {
  results.forEach(result => {
    if (result.isFulfilled()) {
      console.log('OK %j', result);
    } else {
      console.log('WHOOPS %j', result);
    }
  });
});
```

I would expect 'WHOOPS' to be printed out, as the promise inside aPromiseMethod has been rejected. However, OK is actually printed.

If we change aPromiseMethod() to give a reason for failing as a parameter to the reject method, such as in the following code snippet:

```
function aPromiseMethod() {
  return new Promise((resolve, reject) => {
    reject('A reason for failing...');
  });
}
```

'WHOOPS' is printed out, as expected. I am running this code through babel-node incase that makes any difference.

It seems like 'WHOOPS' should be printed even if there is no reason given.

Thanks.

**Comment by omsmith** [comment]
This should be fixed in master (with my changes)

**Comment by DannyBrown-xx** [comment]
Is that version now on NPM? :)

**Comment by pgaubatz** [comment]
Hi!

Thanks for reporting this issue.
I've added a test case, released a new version and uploaded it to npm.

Cheers,
Patrick

**Comment by DannyBrown-xx** [comment]
Thanks, much appreciated.
